//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.saurabh.dada.iq.impl.ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebService;

@WebService(endpointInterface = "com.saurabh.dada.iq.impl.ws.soap.IHelloWorld1")
public class HelloWorld1Impl implements IHelloWorld1 {


	@WebMethod
	public String sayHello(String name) {
		return "Hi, " + name + " v1!";
	}

}
